---
title: "Section A"
author: "Joe Anderson"
date: "01/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Imports
library(Stat2Data)
library(tidyverse)
```

# Scientific Computing and Empirical Methods Summative Assessment Section A
## A.1
```{r}
finance_data_original <- read.csv("Data\\finance_data_EMATM0061.csv")

row_number <- nrow(finance_data_original)
col_number <- ncol(finance_data_original)

print(paste("Number of rows: ", row_number))
print(paste("Number of columns: ", col_number))
```

## A.2 
```{r}
finance_data <- finance_data_original %>%
  select(state_year_code, 
         education_expenditure = Details.Education.Education.Total, 
         health_expenditure = Details.Health.Health.Total.Expenditure, 
         transport_expenditure = Details.Transportation.Highways.Highways.Total.Expenditure, 
         totals_revenue = Totals.Revenue, 
         totals_expenditure = Totals.Expenditure)

finance_data[1:5,1:3]
```
## A.3
```{r}
finance_data <- finance_data %>%
  mutate(total_savings = totals_revenue - totals_expenditure)

print(paste("Number of columns: ", ncol(finance_data)))
finance_data[1:3,c("state_year_code", "totals_revenue", "totals_expenditure", "total_savings")]
```
## A.4
```{r}
# IMPORTANT: only run this cell once, as it will remove the state_year_code column and cause an error
# To run again, run all above cells

finance_data <- finance_data %>%
  separate(state_year_code, into = c("state", "year"), sep = "__", convert = TRUE) 

```

```{r}
#finance_data["state"] <- str_to_title(finance_data["state"])
finance_data["state"] <- str_to_title(pull(finance_data, state))
finance_data[1:3,c("state", "year", "totals_revenue", "totals_expenditure", "total_savings")]

print(paste("Number of columns: ", ncol(finance_data)))
```


## A.5
```{r}
a5_states_data <- finance_data %>%
  filter(state == "Kentucky" | state == "Mississippi" | state == "Montana")
ggplot(data = a5_states_data, aes(x = year, y = totals_revenue, colour = state, linetype = state)) + geom_smooth() + xlab("Year") + ylab("Revenue") + theme_bw()
```

## A.6

```{r}
get_decade <- function(year){
  decade <- floor(year/10) * 10
  return(decade)
}

finance_data <- finance_data %>%
  mutate(decade = get_decade(year))

ncol(finance_data)
head(finance_data)
```

## A.7

```{r}
alaska_summary <- finance_data %>%
  filter(state == "Alaska") %>%
  group_by(decade) %>%
  summarise(ed_mn = mean(education_expenditure, na.rm = 1),
            ed_md = median(education_expenditure, na.rm = 1),
            he_mn = mean(health_expenditure, na.rm = 1),
            he_md = median(health_expenditure, na.rm = 1),
            tr_mn = mean(transport_expenditure, na.rm = 1),
            tr_md = median(transport_expenditure, na.rm = 1))

alaska_summary
```

## A.8
```{r}
impute_by_median = function(x){
  
  md <- median(x, na.rm = 1)
  
  impute_function <- function(y){
    if(is.na(y)){
      return(md)
    }else{
      return(y)
    }
  }
  
  return(map_dbl(x, impute_function))
}
```

```{r}
idaho_2000 <- finance_data %>%
  filter(state == "Idaho" & decade == 2000) %>%
  select(-state, -decade)

idaho_2000_imputed <- idaho_2000 %>% 
  mutate_all(impute_by_median)
  
idaho_2000_imputed[1:5, c("year", "health_expenditure", "education_expenditure", "total_savings")]
```

